# Generated by Django 4.2.7 on 2023-11-13 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0002_remove_entertainments_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_data', models.DateTimeField(default=datetime.datetime(2023, 11, 13, 20, 11, 48, 940019), null=True, verbose_name='Дата создания')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на фото')),
                ('status', models.CharField(max_length=255, verbose_name='Статус ответа')),
            ],
        ),
        migrations.AlterField(
            model_name='entertainments',
            name='start_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 20, 11, 48, 939018), null=True, verbose_name='Время и дата создания запроса.'),
        ),
        migrations.AlterField(
            model_name='joke',
            name='joke_start_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 20, 11, 48, 938018), null=True, verbose_name='Дата создания'),
        ),
    ]
